//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por pia_estructuras.rc
//
#define IDC_MYICON                      2
#define IDCANCEL2                       4
#define IDD_PIAESTRUCTURAS_DIALOG       102
#define IDD_LOGIN                       102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_PIAESTRUCTURAS              107
#define IDI_SMALL                       108
#define IDC_PIAESTRUCTURAS              109
#define IDR_MAINFRAME                   128
#define IDD_PRINCIPAL                   129
#define IDD_REGISTRO                    131
#define IDD_LISTAUSUARIOS               132
#define IDD_DATOSUSUARIO                133
#define IDD_LISTAVUELOS                 134
#define IDD_DATOSVUELO                  135
#define IDD_REGISTRARVUELO              136
#define IDD_LISTAPASAJEROS              137
#define IDD_AGREGARPASAJERO             138
#define IDD_BOLETO                      139
#define IDD_PASEABORDAR                 140
#define IDD_REPORTEVUELOS               141
#define IDD_LISTAREPORTEVUELOS          142
#define IDD_MANIFIESTO                  143
#define IDD_INFOMANIFIESTO              144
#define IDD_DATOSPASAJEROS              145
#define IDD_DIALOG1                     146
#define IDD_CERRARSESION                146
#define IDR_MENU1                       147
#define IDD_REGISTRARADMIN              148
#define IDC_P1                          1000
#define IDC_P2                          1001
#define IDC_P5                          1002
#define IDC_DU1                         1002
#define IDC_P3                          1003
#define IDC_DU2                         1003
#define IDC_P4                          1004
#define IDC_DU3                         1004
#define IDC_P6                          1005
#define IDC_DU4                         1005
#define IDC_P7                          1006
#define IDC_DU5                         1006
#define IDC_DU6                         1007
#define ID_MODUS                        1008
#define ID_AGREGAR                      1009
#define IDC_RU1                         1010
#define IDC_RU2                         1011
#define IDC_RU3                         1012
#define IDC_RU4                         1013
#define IDC_RU5                         1014
#define IDC_RU6                         1015
#define IDC_REGISFOTO                   1016
#define IDC_DATFOTO                     1017
#define IDC_LOGCOMB                     1018
#define IDC_LOGUS                       1020
#define IDC_LOGCON                      1021
#define ID_LV_AGREGAR                   1021
#define IDC_DATETIMEPICKER1             1024
#define IDC_DATETIMEPICKER3             1026
#define IDC_PASENUM                     1027
#define IDC_EDIT1                       1028
#define IDC_EDIT3                       1029
#define IDC_DATETIMEPICKER2             1030
#define IDC_EDIT5                       1031
#define IDC_EDIT6                       1032
#define IDC_EDIT7                       1033
#define IDC_EDIT8                       1034
#define IDC_EDIT9                       1035
#define IDC_FPRINCIPAL                  1036
#define IDC_NPRINCIPAL                  1037
#define IDC_FLVUELOS                    1038
#define IDC_NLVUELOS                    1039
#define IDC_NLUSUARIOS                  1040
#define IDC_FLUSUARIOS                  1041
#define IDC_FDUSUARIO                   1042
#define IDC_NDUSUARIO                   1043
#define IDC_FREGISTRO                   1044
#define IDC_NREGISTRO                   1045
#define IDC_DV1                         1046
#define IDC_DV2                         1047
#define IDC_DV3                         1048
#define IDC_DV4                         1049
#define IDC_DV5                         1050
#define IDC_DV6                         1051
#define IDC_DV7                         1052
#define IDC_LPNUMERO                    1053
#define IDC_NLPASAJEROS                 1055
#define IDC_FLPASAJEROS                 1056
#define IDC_NDVUELO                     1057
#define IDC_FDVUELO                     1058
#define IDC_AP4                         1060
#define IDC_AP3                         1062
#define IDC_LPASAJEROS                  1063
#define IDC_SCROLLBAR1                  1065
#define IDC_LUSUARIOS                   1066
#define IDC_LVUELOS                     1067
#define IDC_AP1                         1068
#define IDC_AP2                         1069
#define IDC_FAPASAJERO                  1070
#define IDC_NAPASAJERO                  1071
#define IDC_COMBO1                      1072
#define IDC_COMBO2                      1073
#define IDC_FPASE                       1074
#define IDC_NPASE                       1075
#define IDC_FREPORTE                    1076
#define IDC_NREPORTE                    1077
#define IDC_REPORTE1                    1078
#define IDC_REPORTE2                    1079
#define IDC_LREPORTEDEVUELOS            1080
#define IDC_ARCHIVOREPORTE              1081
#define IDC_FLREPORTE                   1082
#define IDC_NLREPORTE                   1083
#define IDC_LIST1                       1084
#define IDC_FMANIFIESTO                 1085
#define IDC_NMANIFIESTO                 1086
#define IDC_EDIT2                       1087
#define IDC_EDIT4                       1088
#define IDC_BUTTON1                     1089
#define IDC_FINFOMANI                   1090
#define IDC_NINFOMANI                   1091
#define IDC_FDPASAJERO                  1092
#define IDC_NDPASAJERO                  1093
#define IDC_DP1                         1094
#define IDC_DP2                         1095
#define IDC_DP4                         1097
#define IDC_DP3                         1098
#define IDC_SALIR                       1099
#define IDC_ELIMINAR                    1100
#define IDC_LOGOK                       1102
#define IDC_LOGCANCEL                   1103
#define IDC_AGREGARUS                   1104
#define IDC_REGISTROADMIN               1106
#define ID_AGREGARAdm                   1107
#define ID_MENU_GESTIONDEUSUARIOS       32771
#define ID_MENU_VUELOS                  32772
#define ID_MENU_PASAJEROS               32773
#define ID_MENU_MANIFIESTO              32774
#define ID_MENU_REPORTEDEVUELOS         32775
#define ID_MENU_SALIR                   32776
#define ID_GESTIONDEUSUARIOS_REGISTRARUSUARIOS 32777
#define ID_GESTIONDEUSUARIOS_ELIMINAR   32778
#define ID_GESTIONDEUSUARIOS_VERLISTADEUSUARIOS 32779
#define ID_GESTIONDEUSUARIOS_VERLISTADEUSUARIOS32780 32780
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
